spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/tasks_users?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect # MySQL version
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL of the Eureka server
logging:
  level:
    root: info # Logging level of the application
    org.hibernate.type.descriptor.sql.BasicBinder: trace # Logging level of the SQL queries
    org.hibernate.SQL: trace # Logging level of the SQL queries