server:
  port: 9100
spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: tasks_db
eureka:
  instance:
    hostname: discovery-server # Hostname of the application
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/ # URL of the Eureka server
logging:
  level:
    root: info # Logging level of the application
    org.springframework.data.mongodb.core.MongoTemplate: trace # Logging level of the SQL queries