server:
  port: 9100
spring:
  application:
    name: task-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tasks_db
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL of the Eureka server
logging:
  level:
    root: info # Logging level of the application
    org.springframework.data.mongodb.core.MongoTemplate: trace # Logging level of the SQL queries